name = "acessosvirtual"
compatibility_date = "2026-07-29"
main = "./dist/worker/index.js"

[assets]
directory = "./frontend/dist/frontend/browser"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[d1_databases]]
binding = "DB"
database_name = "painel-clientes-db"
database_id = "8ef81597-513d-4bc1-be12-34366d0ce916"
