name = "acessosvirtual"
pages_build_output_dir = "./frontend/dist/frontend/browser"
compatibility_date = "2026-07-29"

[[d1_databases]]
binding = "DB"
database_name = "painel-clientes-db"
database_id = "8ef81597-513d-4bc1-be12-34366d0ce916"
